{{- range list "inventory" "user" }}
  {{- $service := index $.Values . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  labels:
    app: {{ $service.name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $service.port }}"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          ports:
            - containerPort: {{ $service.port }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: pipo-secrets
                  key: JWT_PRIVATE_KEY
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: pipo-secrets
                  key: JWT_PUBLIC_KEY
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ $service.port }}
            initialDelaySeconds: 100
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ $service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  {{- end }}
