apiVersion: v1
kind: Secret
metadata:
  name: pipo-secrets
type: Opaque
stringData:
  JWT_PRIVATE_KEY: |
{{ .Values.secrets.JWT_PRIVATE_KEY | indent 4 }}
  JWT_PUBLIC_KEY: |
{{ .Values.secrets.JWT_PUBLIC_KEY | indent 4 }}