---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.user.port }}
      targetPort: {{ .Values.user.port }}
      nodePort: {{ .Values.user.nodePort }}
      name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.inventory.port }}
      targetPort: {{ .Values.inventory.port }}
      name: http
  selector:
    app: inventory-service
