spring:
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: user
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  cloud:
    gateway:
      routes:
        - id: api-proxy
          uri: http://localhost:8081
          predicates:
            - Path=/api/**

jwt:
  expiration-time: 10m
  key:
    public: ${JWT_PUBLIC_KEY}
    private: ${JWT_PRIVATE_KEY}