openapi: 3.0.3
info:
  title: Shipment API
  version: v1

tags:
  - name: Auth
    description: Endpoints for registration and login
  - name: Shipment
    description: Endpoints for shipment manipulation
  - name: Supplier
    description: Endpoints for supplier manipulation
  - name: Product
    description: Endpoints for product manipulation
  - name: Zone
    description: Endpoints for zone manipulation
  - name: Location
    description: Endpoints for location manipulation
  - name: Receiver
    description: Endpoints for receiver manipulation
  - name: Stock
    description: Endpoints for stock manipulation
  - name: Outbound
    description: Endpoints for withdrawal manipulation

paths:
  /public/auth/register:
    post:
      tags: [ Auth ]
      summary: Register new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /public/auth/login:
    post:
      tags: [ Auth ]
      summary: Login
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/v1/shipment:
    post:
      tags: [ Shipment ]
      summary: register shipment
      operationId: createShipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShipmentRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentResponse'
  /api/v1/shipment/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer, format: int64 }
      tags: [ Shipment ]
      summary: get shipment
      operationId: getShipment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentResponse'
  /api/v1/shipmentUnit:
    post:
      tags: [ Shipment ]
      summary: register shipment unit
      operationId: createShipmentUnit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShipmentUnitRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentUnitResponse'
  /api/v1/shipmentUnit/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer, format: int64 }
    get:
      tags: [ Shipment ]
      summary: get shipment unit
      operationId: getShipmentUnit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentUnitResponse'
    put:
      tags: [ Shipment ]
      summary: move shipment unit
      operationId: moveShipmentUnit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoveShipmentUnitRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipmentUnitResponse'
  /api/v1/supplier:
    post:
      tags: [ Supplier ]
      summary: register supplier
      operationId: createSupplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSupplierRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
  /api/v1/supplier/{code}:
    parameters:
      - name: code
        in: path
        required: true
        schema: { type: string }
    get:
      tags: [ Supplier ]
      summary: get supplier info
      operationId: getSupplier
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
    patch:
      tags: [ Supplier ]
      summary: patch supplier
      operationId: patchSupplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchSupplierRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
  /api/v1/product:
    post:
      tags: [ Product ]
      summary: register product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
  /api/v1/product/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Product ]
      summary: get product
      operationId: getProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
  /api/v1/zone:
    post:
      tags: [ Zone ]
      summary: register zone
      operationId: createZone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateZoneRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZoneResponse'
  /api/v1/zone/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Zone ]
      summary: get zone
      operationId: getZone
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZoneResponse'
    delete:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Zone ]
      summary: delete zone
      operationId: deleteZone
      responses:
        '204':
          description: OK
  /api/v1/locationType:
    post:
      tags: [ Location ]
      summary: register location type
      operationId: createLocationType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLocationTypeRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationTypeResponse'
  /api/v1/locationType/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Location ]
      summary: get location type
      operationId: getLocationType
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationTypeResponse'
    delete:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Location ]
      summary: delete location type
      operationId: deleteLocationType
      responses:
        '204':
          description: OK
  /api/v1/location:
    post:
      tags: [ Location ]
      summary: register location
      operationId: createLocation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLocationRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationResponse'
  /api/v1/location/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Location ]
      summary: get location
      operationId: getLocation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationResponse'
    delete:
      parameters:
        - name: code
          in: path
          required: true
          schema: { type: string }
      tags: [ Location ]
      summary: delete location
      operationId: deleteLocation
      responses:
        '204':
          description: OK
  /api/v1/receiver:
    post:
      tags: [ Receiver ]
      summary: register receiver
      operationId: createReceiver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReceiverRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceiverResponse'
  /api/v1/receiver/{code}:
    parameters:
      - name: code
        in: path
        required: true
        schema: { type: string }
    get:
      tags: [ Receiver ]
      summary: get receiver info
      operationId: getReceiver
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReceiverResponse'
  /api/v1/outboundShipment:
    post:
      tags: [ Outbound ]
      summary: register outbound shipment
      operationId: createOutboundShipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOutboundShipmentRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundShipmentResponse'
  /api/v1/outboundShipment/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: integer, format: int64 }
    get:
      tags: [ Outbound ]
      summary: get outbound shipment info
      operationId: getOutboundShipment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutboundShipmentResponse'

components:
  schemas:
    RegisterRequest:
      type: object
      required: [ username, password ]
      properties:
        username: { type: string }
        password: { type: string }

    LoginRequest:
      type: object
      required: [ username, password ]
      properties:
        username: { type: string }
        password: { type: string }

    AuthResponse:
      type: object
      properties:
        token: { type: string }

    CreateShipmentRequest:
      type: object
      required: [ supplierCode, productCode, shipmentUnitCount ]
      properties:
        supplierCode: { type: string }
        externalShipmentId: { type: string }
        productCode: { type: string }
        shipmentUnitCount: { type: integer, format: int64 }
    ShipmentResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        supplierCode: { type: string }
        externalShipmentId: { type: string }
        productCode: { type: string }
        status: { type: string }
        shipmentUnitCount: { type: integer, format: int64 }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateShipmentUnitRequest:
      type: object
      required: [ shipmentId, amount, lengthCm, widthCm, heightCm ]
      properties:
        shipmentId: { type: integer, format: int64 }
        amount: { type: integer, format: int64 }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
    MoveShipmentUnitRequest:
      type: object
      required: [ locationCode ]
      properties:
        locationCode: { type: string }
    ShipmentUnitResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        shipmentId: { type: integer, format: int64 }
        shipmentStatus: { type: string }
        locationCode: { type: string }
        amount: { type: integer, format: int64 }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateSupplierRequest:
      type: object
      required: [ name, code ]
      properties:
        name: { type: string }
        code: { type: string }
    PatchSupplierRequest:
      type: object
      properties:
        name: { type: string }
        code: { type: string }
    SupplierResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        code: { type: string }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateProductRequest:
      type: object
      required: [ code, name, length, width, height ]
      properties:
        code: { type: string }
        name: { type: string }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
    ProductResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        code: { type: string }
        name: { type: string }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateZoneRequest:
      type: object
      required: [ code, type ]
      properties:
        code: { type: string }
        type: { type: string }
    ZoneResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        code: { type: string }
        type: { type: string }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateLocationTypeRequest:
      type: object
      required: [ code ]
      properties:
        code: { type: string }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
        unlimited: { type: boolean, default: false }
    LocationTypeResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        code: { type: string }
        lengthCm: { type: integer, format: int64 }
        widthCm: { type: integer, format: int64 }
        heightCm: { type: integer, format: int64 }
        unlimited: { type: boolean }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateLocationRequest:
      type: object
      required: [ code, locationTypeCode, zoneCode ]
      properties:
        code: { type: string }
        locationTypeCode: { type: string }
        zoneCode: { type: string }
    LocationResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        code: { type: string }
        locationTypeCode: { type: string }
        zoneCode: { type: string }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateReceiverRequest:
      type: object
      required: [ code, name ]
      properties:
        code: { type: string }
        name: { type: string }
    ReceiverResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        code: { type: string }
        name: { type: string }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    CreateOutboundShipmentRequest:
      type: object
      required: [ receiverCode, products ]
      properties:
        receiverCode: { type: string }
        externalShipmentId: { type: string }
        products:
          type: array
          required: [ productCode, productCount ]
          items:
            type: object
            properties:
              productCode: { type: string }
              productCount: { type: integer, format: int64 }
    OutboundShipmentResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        receiverCode: { type: string }
        externalShipmentId: { type: string }
        status: { type: string }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
