spring:
  servers:
    - url : ${SERVER_URL}
      description: inventory-service
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: inventory
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
